-- MySQL Script generated by MySQL Workbench
-- Wed Feb 21 12:02:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dispositivo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `MAC` VARCHAR(12) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Fabricante` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Autorização` DATE NULL,
  `Ultima_Atualização` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assinatura` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Status` ENUM('Ativo', 'Cancelado') NOT NULL,
  `Data_Inicio` DATE NOT NULL,
  `Data_Término` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  `Id_Dispositivo` VARCHAR(45) NOT NULL,
  `Id_Assinatura` INT NOT NULL,
  `Created_at` TIMESTAMP(20) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`, `Email`),
  INDEX `fk_TB-USUÁRIO_TB-Dispositivo1_idx` (`Id_Dispositivo` ASC) VISIBLE,
  INDEX `fk_TB-USUÁRIO_ASSINATURA1_idx` (`Id_Assinatura` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_TB-USUÁRIO_TB-Dispositivo1`
    FOREIGN KEY (`Id_Dispositivo`)
    REFERENCES `mydb`.`Dispositivo` (`MAC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB-USUÁRIO_ASSINATURA1`
    FOREIGN KEY (`Id_Assinatura`)
    REFERENCES `mydb`.`Assinatura` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Playlist` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Descricao` MEDIUMTEXT NULL,
  `Created_at` TIMESTAMP(10) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Idioma` ENUM('Portugês', 'Inglês') NOT NULL,
  `Legenda` ENUM('Português', 'Inglês') NOT NULL,
  `TB-USUARIO_EMAIL` VARCHAR(200) NOT NULL,
  `TB-USUARIO_CPF` VARCHAR(11) NOT NULL,
  `Playlist_ID_Playlist` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Perfil_TB-USUÁRIO1_idx` (`TB-USUARIO_EMAIL` ASC, `TB-USUARIO_CPF` ASC) VISIBLE,
  INDEX `fk_Perfil_Playlist1_idx` (`Playlist_ID_Playlist` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_TB-USUÁRIO1`
    FOREIGN KEY (`TB-USUARIO_EMAIL` , `TB-USUARIO_CPF`)
    REFERENCES `mydb`.`Usuario` (`Email` , `CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_Playlist1`
    FOREIGN KEY (`Playlist_ID_Playlist`)
    REFERENCES `mydb`.`Playlist` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visualizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visualizacao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `STATUS` ENUM('Assistido', 'Incompleto') NOT NULL,
  `PROGRESSO` FLOAT NULL,
  `Id_Perfil` INT NOT NULL,
  INDEX `fk_Visualizacao_Perfil1_idx` (`Id_Perfil` ASC) VISIBLE,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_Visualizacao_Perfil1`
    FOREIGN KEY (`Id_Perfil`)
    REFERENCES `mydb`.`Perfil` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conteúdo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conteúdo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descrição` MEDIUMTEXT NULL,
  `Genero[]` ENUM('Terror', 'Ação') NOT NULL,
  `Classficação` ENUM('Livre', '10') NOT NULL,
  `Data_Lancamento` FLOAT NOT NULL,
  `Idioma[]` ENUM('Português', 'Inglês') NOT NULL,
  `Legenda[]` ENUM('Português', 'Inglês') NULL,
  `Ator[]` VARCHAR(45) NULL,
  `Diretor[]` VARCHAR(45) NULL,
  `Série_ID_Conteúdo` INT NOT NULL,
  PRIMARY KEY (`Id`, `Série_ID_Conteúdo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filme` (
  `Sinopse` MEDIUMTEXT NULL,
  `Orçamento` FLOAT NULL,
  `Premiações` VARCHAR(45) NULL,
  `Conteúdo_ID_Conteúdo` INT NOT NULL,
  PRIMARY KEY (`Conteúdo_ID_Conteúdo`),
  INDEX `fk_Filme_Conteúdo_idx` (`Conteúdo_ID_Conteúdo` ASC) VISIBLE,
  CONSTRAINT `fk_Filme_Conteúdo`
    FOREIGN KEY (`Conteúdo_ID_Conteúdo`)
    REFERENCES `mydb`.`Conteúdo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documentário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documentário` (
  `Tema` VARCHAR(45) NULL,
  `Narrador` VARCHAR(45) NULL,
  `Data_Produção` DATE NULL,
  `Orçamento` FLOAT NULL,
  `Entrevistado` VARCHAR(45) NULL,
  `Conteúdo_ID_Conteúdo` INT NOT NULL,
  PRIMARY KEY (`Conteúdo_ID_Conteúdo`),
  INDEX `fk_Documentário_Conteúdo1_idx` (`Conteúdo_ID_Conteúdo` ASC) VISIBLE,
  CONSTRAINT `fk_Documentário_Conteúdo1`
    FOREIGN KEY (`Conteúdo_ID_Conteúdo`)
    REFERENCES `mydb`.`Conteúdo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Série`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Série` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Título` VARCHAR(45) NOT NULL,
  `Descrição` MEDIUMTEXT NULL,
  `Gênero` ENUM('Ação', 'Terror') NULL,
  `Classificação_Indicativa` ENUM('Livre', '10') NULL,
  `Status` ENUM('Lançamento', 'Em Breve') NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temporada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Temporada` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Número` INT NOT NULL,
  `Ano_Lancamento` YEAR(1) NULL,
  `Descrição` MEDIUMTEXT NULL,
  `Status` ENUM('Lançamento', 'Em Breve') NOT NULL,
  `Série_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Série_Id`),
  INDEX `fk_Temporada_Série1_idx` (`Série_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Temporada_Série1`
    FOREIGN KEY (`Série_Id`)
    REFERENCES `mydb`.`Série` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Episódio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Episódio` (
  `Número` INT NOT NULL,
  `Subtitulo` VARCHAR(45) NULL,
  `Sinopse` MEDIUMTEXT NULL,
  `Roteirista` VARCHAR(45) NULL,
  `Ator[]` VARCHAR(45) NULL,
  `Conteúdo_Id` INT NOT NULL,
  `Temporada_Id` INT NOT NULL,
  PRIMARY KEY (`Conteúdo_Id`, `Temporada_Id`),
  INDEX `fk_Episódio_Conteúdo1_idx` (`Conteúdo_Id` ASC) VISIBLE,
  INDEX `fk_Episódio_Temporada1_idx` (`Temporada_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Episódio_Conteúdo1`
    FOREIGN KEY (`Conteúdo_Id`)
    REFERENCES `mydb`.`Conteúdo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Episódio_Temporada1`
    FOREIGN KEY (`Temporada_Id`)
    REFERENCES `mydb`.`Temporada` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plano` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Tipo` ENUM('Mensal', 'Anual') NOT NULL,
  `Preço` FLOAT NOT NULL,
  `Número_Dispositivos` INT NOT NULL,
  `Id_Assinatura` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Plano_ASSINATURA1_idx` (`Id_Assinatura` ASC) INVISIBLE,
  CONSTRAINT `fk_Plano_ASSINATURA1`
    FOREIGN KEY (`Id_Assinatura`)
    REFERENCES `mydb`.`Assinatura` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Legenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Legenda` (
  `Idioma` ENUM('Português', 'Inglês') NOT NULL,
  `Path` VARCHAR(45) NOT NULL,
  `Conteúdo_ID_Conteúdo` INT NOT NULL,
  `Conteúdo_Série_ID_Conteúdo` INT NOT NULL,
  INDEX `fk_Legenda_Conteúdo1_idx` (`Conteúdo_ID_Conteúdo` ASC, `Conteúdo_Série_ID_Conteúdo` ASC) VISIBLE,
  CONSTRAINT `fk_Legenda_Conteúdo1`
    FOREIGN KEY (`Conteúdo_ID_Conteúdo` , `Conteúdo_Série_ID_Conteúdo`)
    REFERENCES `mydb`.`Conteúdo` (`Id` , `Série_ID_Conteúdo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtora` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Pais` VARCHAR(45) NULL,
  `Data_Fundacao` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produz` (
  `Conteúdo_ID_Conteúdo` INT NOT NULL,
  `Conteúdo_Série_ID_Conteúdo` INT NOT NULL,
  `Produtora_ID_Produtora` INT NOT NULL,
  PRIMARY KEY (`Conteúdo_ID_Conteúdo`, `Conteúdo_Série_ID_Conteúdo`, `Produtora_ID_Produtora`),
  INDEX `fk_Conteúdo_has_Produtora_Produtora1_idx` (`Produtora_ID_Produtora` ASC) VISIBLE,
  INDEX `fk_Conteúdo_has_Produtora_Conteúdo1_idx` (`Conteúdo_ID_Conteúdo` ASC, `Conteúdo_Série_ID_Conteúdo` ASC) VISIBLE,
  CONSTRAINT `fk_Conteúdo_has_Produtora_Conteúdo1`
    FOREIGN KEY (`Conteúdo_ID_Conteúdo` , `Conteúdo_Série_ID_Conteúdo`)
    REFERENCES `mydb`.`Conteúdo` (`Id` , `Série_ID_Conteúdo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conteúdo_has_Produtora_Produtora1`
    FOREIGN KEY (`Produtora_ID_Produtora`)
    REFERENCES `mydb`.`Produtora` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contem` (
  `Conteúdo_ID_Conteúdo` INT NOT NULL,
  `Conteúdo_Série_ID_Conteúdo` INT NOT NULL,
  `Playlist_ID_Playlist` INT NOT NULL,
  PRIMARY KEY (`Conteúdo_ID_Conteúdo`, `Conteúdo_Série_ID_Conteúdo`, `Playlist_ID_Playlist`),
  INDEX `fk_Conteúdo_has_Playlist_Playlist1_idx` (`Playlist_ID_Playlist` ASC) VISIBLE,
  INDEX `fk_Conteúdo_has_Playlist_Conteúdo1_idx` (`Conteúdo_ID_Conteúdo` ASC, `Conteúdo_Série_ID_Conteúdo` ASC) VISIBLE,
  CONSTRAINT `fk_Conteúdo_has_Playlist_Conteúdo1`
    FOREIGN KEY (`Conteúdo_ID_Conteúdo` , `Conteúdo_Série_ID_Conteúdo`)
    REFERENCES `mydb`.`Conteúdo` (`Id` , `Série_ID_Conteúdo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conteúdo_has_Playlist_Playlist1`
    FOREIGN KEY (`Playlist_ID_Playlist`)
    REFERENCES `mydb`.`Playlist` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao` (
  `Perfil_ID_Perfil` INT NOT NULL,
  `Conteúdo_ID_Conteúdo` INT NOT NULL,
  `Conteúdo_Série_ID_Conteúdo` INT NOT NULL,
  `Visualizacao_ID_visualizacao` INT NOT NULL,
  `Data` DATE NULL,
  `Classificacao` VARCHAR(2) NULL,
  `Comentario` MEDIUMTEXT NULL,
  PRIMARY KEY (`Perfil_ID_Perfil`, `Conteúdo_ID_Conteúdo`, `Conteúdo_Série_ID_Conteúdo`, `Visualizacao_ID_visualizacao`),
  INDEX `fk_Perfil_has_Conteúdo_Conteúdo1_idx` (`Conteúdo_ID_Conteúdo` ASC, `Conteúdo_Série_ID_Conteúdo` ASC) VISIBLE,
  INDEX `fk_Perfil_has_Conteúdo_Perfil1_idx` (`Perfil_ID_Perfil` ASC) VISIBLE,
  INDEX `fk_avaliacao_Visualizacao1_idx` (`Visualizacao_ID_visualizacao` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_has_Conteúdo_Perfil1`
    FOREIGN KEY (`Perfil_ID_Perfil`)
    REFERENCES `mydb`.`Perfil` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_has_Conteúdo_Conteúdo1`
    FOREIGN KEY (`Conteúdo_ID_Conteúdo` , `Conteúdo_Série_ID_Conteúdo`)
    REFERENCES `mydb`.`Conteúdo` (`Id` , `Série_ID_Conteúdo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_Visualizacao1`
    FOREIGN KEY (`Visualizacao_ID_visualizacao`)
    REFERENCES `mydb`.`Visualizacao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Titular` VARCHAR(45) NOT NULL,
  `Numero_Cartao` VARCHAR(20) NOT NULL,
  `Validade` DATE NOT NULL,
  `CVC` MEDIUMINT(3) NOT NULL,
  `Modalidade` ENUM('Credito', 'Debito') NOT NULL,
  `Id_Assinatura` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Id_Assinarura_idx` (`Id_Assinatura` ASC) VISIBLE,
  CONSTRAINT `Id_Assinarura`
    FOREIGN KEY (`Id_Assinatura`)
    REFERENCES `mydb`.`Assinatura` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
