name: Teste de Aplicação

on:
  pull_request:
    branches:
      - main

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"

      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes
        run: npm run test

      - name: Finalizar
        run: echo "Testes concluídos com sucesso!"
